openapi: "3.0.0"
info:
  version: 1.0.0
  title: Igor's Happy Birthday service
  description: Happy Birthday notify you!
  termsOfService: https://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: https://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /auth/register:
    post:
      summary: User registration
      description: Handler make new user ristration
      operationId: CreateUser
      parameters:
      requestBody:
        description: User add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'  
      responses:
        '201':
          description: User created, return OTP secret
          content:
            plain/text:
              schema:
                type: string
                format: string
        '400':
          description: Error creating hash from password
        '401':
          description: user has no otp pass, create new
        '409':
          description: Login is used
        '500':
          description: Can't get UUID or user hash 
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/login:
    post:
      summary: User login
      description: Handler make existing user auth (login)
      operationId: Login
      parameters:
      requestBody:
        description: Login New User
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'  
      responses:
        '200':
          description: Successful login
        '400':
          description: Error decode json
        '401':
          description: Wrong login or password
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      allOf:
        - $ref: '#/components/schemas/NewUser'
        - required:
            - userID
          properties:
            userID:
              type: string
              format: string
              description: User id
    NewUser:
      required:
        - login
        - password
        - email
        - otp
      properties:
        login:
          type: string
          description: User login from registration
        password:
          type: string
          description: User pass from registartion
        email:
          type: string
          description: Users email
        otp:
          type: string
          description: User's one time pass
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message